### ISSUE TITLE
[Notice] 该项目被废弃

### ISSUE THREAD

**Issue by Himself65** [Himself65/vscode-luogu#36]
www.luogu.org 网站仅有的几个API不适合制作luogu插件，本人没有兴趣对此投入时间，故废弃

有兴趣者可以向我申请Collaborator权限继续维护

**Comment by abc1763613206** [comment]
如此封闭，怕是只能搞个爬虫地下运行了

**Comment by yltx** [comment]
> [www.luogu.org](http://www.luogu.org) 网站仅有的几个API不适合制作luogu插件，本人没有兴趣对此投入时间，故废弃
> 
> 有兴趣者可以向我申请Collaborator权限继续维护

QAQ要不我来管管吧，我争取从您以前的版本中抠出一个，然后跟现有的合并一下，争取把您历史上支持过的功能都支持上

**Comment by yltx** [comment]
> [www.luogu.org](http://www.luogu.org) 网站仅有的几个API不适合制作luogu插件，本人没有兴趣对此投入时间，故废弃
> 
> 有兴趣者可以向我申请Collaborator权限继续维护

您历史上能支持登录&提交题目的是哪个版本啊

**Comment by Lutra-Fs** [comment]
@yltx 应至少追溯至该commit [50e2b1](https://github.com/Himself65/vscode-luogu/commit/50e2b1912bdc5bd6a2c97bdb12aa0cde6ea3bb07)

**Comment by yltx** [comment]
> @yltx 应至少追溯至该commit [50e2b1](https://github.com/Himself65/vscode-luogu/commit/50e2b1912bdc5bd6a2c97bdb12aa0cde6ea3bb07)

那么版本是哪个呢

**Comment by onelittlechildawa** [comment]
no我还等着呢……

**Comment by yltx** [comment]
> no我还等着呢……

我康main包的代码没看懂，然后被main包喷了一下，现在我也不怎么想管这个事了……或许就只能让它停更了2333

**Comment by HoshinoTented** [comment]
想要维护这个项目，但自己并不会JavaScript QAQ

**Comment by onelittlechildawa** [comment]
23333 我们找个大佬来弄吧





在 NaN-NaN-NaN NaN:NaN:NaN，"Hoshino Tented" <notifications@github.com> 写道：


想要维护这个项目，但自己并不会JavaScript QAQ

**Comment by RoderickQiu** [comment]
> 
> 
> 想要维护这个项目，但自己并不会JavaScript QAQ

但是这不是TypeScript嘛。

**Comment by yltx** [comment]
> > 想要维护这个项目，但自己并不会JavaScript QAQ
> 
> 但是这不是TypeScript嘛。

您会吗QAQ

**Comment by HoshinoTented** [comment]
我也不会typedcript，不过倒是会Kotlin

**Comment by RoderickQiu** [comment]
> 
> 
> > > 想要维护这个项目，但自己并不会JavaScript QAQ
> > 
> > 
> > 但是这不是TypeScript嘛。
> 
> 您会吗QAQ

会一点js和es6，ts没入过坑，不清楚。

**Comment by RoderickQiu** [comment]
其实现在这个东西（vscode-luogu）最坑的一点是对样式和公式的支持实在欠佳。

**Comment by RoderickQiu** [comment]
> 
> 
> 我也不会typedcript，不过倒是会Kotlin

不过好像在哪看见过说typescript只是js的超集而已，应该学习成本还好。

**Comment by onelittlechildawa** [comment]
我们重构代码非常困难吗

**Comment by YanWQ-monad** [comment]
想维护，也会 TypeScript（之前写 OJ 的时候用过），也有经验（写过 Sublime 插件）  
可是问题是没有时间（有也不会很多），高二了教练要求专心搞竞赛 orz。

注：用过 != 精通

**Comment by jyeric** [comment]
洛谷的API各种神奇，验证码也比较难处理

**Comment by yltx** [comment]
> 洛谷的API各种神奇，验证码也比较难处理

2333

**Comment by YanWQ-monad** [comment]
唉，基本上没有哪个网站是积极公开 API 的，甚至还弄一大堆反爬。

之前搞 SmojSubmit 的时候，写正则读取网页数据的时候欲死欲仙的。  
然后搞洛谷的时候：验证码？下载下来让用户输入。XSRF？“手动”读取页面的 `X-CSRF-Token`。  
~~佛了，没有 API 寸步难行~~

**Comment by yltx** [comment]
> 唉，基本上没有哪个网站是积极公开 API 的，甚至还弄一大堆反爬。
> 
> 之前搞 SmojSubmit 的时候，写正则读取网页数据的时候欲死欲仙的。
> 然后搞洛谷的时候：验证码？下载下来让用户输入。XSRF？“手动”读取页面的 `X-CSRF-Token`。
> ~佛了，没有 API 寸步难行~

sm.ms

https://code.visualstudio.com/api

**Comment by YanWQ-monad** [comment]
> > 唉，基本上没有哪个网站是积极公开 API 的，甚至还弄一大堆反爬。
> > 之前搞 SmojSubmit 的时候，写正则读取网页数据的时候欲死欲仙的。
> > 然后搞洛谷的时候：验证码？下载下来让用户输入。XSRF？“手动”读取页面的 `X-CSRF-Token`。
> > ~佛了，没有 API 寸步难行~
> 
> sm.ms
> 
> https://code.visualstudio.com/api

怎么能忽略 [GitHub](https://api.github.com) 呢

**Comment by yltx** [comment]
> > > 唉，基本上没有哪个网站是积极公开 API 的，甚至还弄一大堆反爬。
> > > 之前搞 SmojSubmit 的时候，写正则读取网页数据的时候欲死欲仙的。
> > > 然后搞洛谷的时候：验证码？下载下来让用户输入。XSRF？“手动”读取页面的 `X-CSRF-Token`。
> > > ~佛了，没有 API 寸步难行~
> > 
> > 
> > sm.ms
> > https://code.visualstudio.com/api
> 
> 怎么能忽略 [GitHub](https://api.github.com) 呢

2333

**Comment by HoshinoTented** [comment]
https://github.com/HoshinoTented/LuoGuAPI
然而这里明明有现成的（推销一波项目赶紧溜

**Comment by himself65** [comment]
> > > 唉，基本上没有哪个网站是积极公开 API 的，甚至还弄一大堆反爬。
> > > 之前搞 SmojSubmit 的时候，写正则读取网页数据的时候欲死欲仙的。
> > > 然后搞洛谷的时候：验证码？下载下来让用户输入。XSRF？“手动”读取页面的 `X-CSRF-Token`。
> > > ~佛了，没有 API 寸步难行~
> > 
> > 
> > sm.ms
> > https://code.visualstudio.com/api
> 
> 怎么能忽略 [GitHub](https://api.github.com) 呢

本身是给以服务程序员为中心，各种API也是为了更好宣传自己

OJ明显没有这个需求，写算法题和api本身没什么矛盾，其次各OJ创立时也不考虑此问题

**Comment by HoshinoTented** [comment]
然而其实最近洛谷的重构有在美化API，现在的API已经算是好用了

**Comment by guodong2005** [comment]
如果我们捐赠到一定数额,您会继续搞吗?

**Comment by HoshinoTented** [comment]
面包：我不铲屎

**Comment by himself65** [comment]
依情况而定

**Comment by yltx** [comment]
咕咕咕
